### ISSUE TITLE
Where is your thumbnail in your demo?

### ISSUE THREAD

**Issue by NanyangTaiji** [Reone/Mrthumb#1]

**Comment by Reone** [comment]
What thumbnail are you talking about?
1. Is the picture in README.md? At [preview.gif](https://github.com/Reone/Mrthumb/blob/master/simple/preview.gif)
2. The thumbnails displayed in the demo are loaded from the video stream, and the video stream is from the network.
3. Or where is the thumbnail saved? There is a Bitmap[] thumbnails; at [ThumbThread.java](https://github.com/Reone/Mrthumb/blob/master-1.0.2/mrthumb/src/main/java/com/reone/mrthumb/core/ThumbThread.java). Generally, thumbnails do not need to be large 320*180, and only need 100 sheets. There is currently no cache in the project, and it is possible to do it later.
