### ISSUE TITLE
支持m3u8缩略图截取吗？

### ISSUE THREAD

**Issue by fudaye** [Reone/Mrthumb#2]
您好，我在demo中使用 http://demo2-live.tianchiapi.com/group1/epg/5c78a8a1e5dad94294c3cf23/1591855800_1591858800.m3u8 这个测试地址发现无法截取缩略图而且 process处理起来也非常慢，请问有什么好建议吗？

**Comment by Reone** [comment]
目前不支持这个格式（如果是直播流的，也无法获取缩略图），process处理慢主要是慢在获取某一帧的缩略图过程。
如果你的项目非常注重缩略图，建议在服务端事先保存好对应视频的一组缩略图，这才是正道。

**Comment by Reone** [comment]
如果觉得Mrthumb好用的话，你可以自定义一个process，继承CacheProcess，在start的时候请求缩略图，在get的时候获取请求下来的缩略图。

**Comment by Reone** [comment]
后续版本我会尝试一下

**Comment by fudaye** [comment]
非常感谢  比心
