### ISSUE TITLE
如果不需要缓存了

### ISSUE THREAD

**Issue by 183883324** [Reone/Mrthumb#3]
老哥 我只是做预览  不需要缓存 视频帧    类似抖音  视频比较短 然后滑动的时候能看到缩略图就行  能不能指教下

**Comment by Reone** [comment]
缓存是为了滑动的时候快速的得到bitmap。如果不需要的话，你可以直接使用FFmpeg的方法，通过毫秒去获取某个点的某一帧：`getScaledFrameAtTime()`
